{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.10.10","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"code","source":"# This Python 3 environment comes with many helpful analytics libraries installed\n# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python\n# For example, here's several helpful packages to load\n\nimport numpy as np # linear algebra\nimport pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)\n\n# Input data files are available in the read-only \"../input/\" directory\n# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory\n\nimport os\nfor dirname, _, filenames in os.walk('/kaggle/input'):\n    for filename in filenames:\n        print(os.path.join(dirname, filename))\n\n# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using \"Save & Run All\" \n# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","execution":{"iopub.status.busy":"2023-05-20T02:59:34.612608Z","iopub.execute_input":"2023-05-20T02:59:34.613428Z","iopub.status.idle":"2023-05-20T02:59:34.645273Z","shell.execute_reply.started":"2023-05-20T02:59:34.613394Z","shell.execute_reply":"2023-05-20T02:59:34.644296Z"},"trusted":true},"execution_count":1,"outputs":[{"name":"stdout","text":"/kaggle/input/search-data-1/data.json\n/kaggle/input/search-data/questions.json\n/kaggle/input/search-data/sentences.json\n/kaggle/input/search-index/index_faiss_sbert.index\n","output_type":"stream"}]},{"cell_type":"code","source":"!pip install faiss-gpu","metadata":{"execution":{"iopub.status.busy":"2023-05-20T02:59:43.040855Z","iopub.execute_input":"2023-05-20T02:59:43.041328Z","iopub.status.idle":"2023-05-20T02:59:57.552912Z","shell.execute_reply.started":"2023-05-20T02:59:43.041289Z","shell.execute_reply":"2023-05-20T02:59:57.551793Z"},"trusted":true},"execution_count":2,"outputs":[{"name":"stdout","text":"Collecting faiss-gpu\n  Downloading faiss_gpu-1.7.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (85.5 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m85.5/85.5 MB\u001b[0m \u001b[31m13.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n\u001b[?25hInstalling collected packages: faiss-gpu\nSuccessfully installed faiss-gpu-1.7.2\n\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n\u001b[0m","output_type":"stream"}]},{"cell_type":"code","source":"import json\nimport faiss\n\nwith open('/kaggle/input/search-data-1/data.json','r') as file:\n    data=json.load(file)\n\n\nwith open('/kaggle/input/search-data/questions.json','r') as file:\n    questions=json.load(file)\n    \nindex=faiss.read_index('/kaggle/input/search-index/index_faiss_sbert.index')\n","metadata":{"execution":{"iopub.status.busy":"2023-05-20T03:04:03.316104Z","iopub.execute_input":"2023-05-20T03:04:03.316952Z","iopub.status.idle":"2023-05-20T03:04:03.330100Z","shell.execute_reply.started":"2023-05-20T03:04:03.316913Z","shell.execute_reply":"2023-05-20T03:04:03.329077Z"},"trusted":true},"execution_count":12,"outputs":[]},{"cell_type":"code","source":"from transformers import pipeline\nqa_model=pipeline(task=\"question-answering\",model=\"deepset/roberta-base-squad2\")\n#model(\"Who is the president of the United States?\")","metadata":{"execution":{"iopub.status.busy":"2023-05-20T03:07:17.696171Z","iopub.execute_input":"2023-05-20T03:07:17.696955Z","iopub.status.idle":"2023-05-20T03:07:19.623901Z","shell.execute_reply.started":"2023-05-20T03:07:17.696917Z","shell.execute_reply":"2023-05-20T03:07:19.622933Z"},"trusted":true},"execution_count":16,"outputs":[]},{"cell_type":"code","source":"!pip install sentence-transformers","metadata":{"execution":{"iopub.status.busy":"2023-05-20T03:00:40.052241Z","iopub.execute_input":"2023-05-20T03:00:40.052601Z","iopub.status.idle":"2023-05-20T03:00:53.451191Z","shell.execute_reply.started":"2023-05-20T03:00:40.052570Z","shell.execute_reply":"2023-05-20T03:00:53.449918Z"},"trusted":true},"execution_count":5,"outputs":[{"name":"stdout","text":"Collecting sentence-transformers\n  Downloading sentence-transformers-2.2.2.tar.gz (85 kB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m86.0/86.0 kB\u001b[0m \u001b[31m5.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25ldone\n\u001b[?25hRequirement already satisfied: transformers<5.0.0,>=4.6.0 in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (4.28.1)\nRequirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (4.64.1)\nRequirement already satisfied: torch>=1.6.0 in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (2.0.0)\nRequirement already satisfied: torchvision in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (0.15.1)\nRequirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (1.23.5)\nRequirement already satisfied: scikit-learn in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (1.2.2)\nRequirement already satisfied: scipy in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (1.9.3)\nRequirement already satisfied: nltk in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (3.2.4)\nRequirement already satisfied: sentencepiece in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (0.1.98)\nRequirement already satisfied: huggingface-hub>=0.4.0 in /opt/conda/lib/python3.10/site-packages (from sentence-transformers) (0.13.4)\nRequirement already satisfied: typing-extensions>=3.7.4.3 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.4.0->sentence-transformers) (4.5.0)\nRequirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.4.0->sentence-transformers) (6.0)\nRequirement already satisfied: packaging>=20.9 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.4.0->sentence-transformers) (21.3)\nRequirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.4.0->sentence-transformers) (3.11.0)\nRequirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.4.0->sentence-transformers) (2.28.2)\nRequirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch>=1.6.0->sentence-transformers) (1.11.1)\nRequirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch>=1.6.0->sentence-transformers) (3.1.2)\nRequirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch>=1.6.0->sentence-transformers) (3.1)\nRequirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /opt/conda/lib/python3.10/site-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers) (0.13.3)\nRequirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers) (2023.3.23)\nRequirement already satisfied: six in /opt/conda/lib/python3.10/site-packages (from nltk->sentence-transformers) (1.16.0)\nRequirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn->sentence-transformers) (3.1.0)\nRequirement already satisfied: joblib>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from scikit-learn->sentence-transformers) (1.2.0)\nRequirement already satisfied: pillow!=8.3.*,>=5.3.0 in /opt/conda/lib/python3.10/site-packages (from torchvision->sentence-transformers) (9.5.0)\nRequirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging>=20.9->huggingface-hub>=0.4.0->sentence-transformers) (3.0.9)\nRequirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch>=1.6.0->sentence-transformers) (2.1.2)\nRequirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (2.1.1)\nRequirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (1.26.15)\nRequirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (2022.12.7)\nRequirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (3.4)\nRequirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch>=1.6.0->sentence-transformers) (1.3.0)\nBuilding wheels for collected packages: sentence-transformers\n  Building wheel for sentence-transformers (setup.py) ... \u001b[?25ldone\n\u001b[?25h  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=f77369ffbcd0485e406835cc18b0dcad93e840387d992dbf60c39bd0b5f819ad\n  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f\nSuccessfully built sentence-transformers\nInstalling collected packages: sentence-transformers\nSuccessfully installed sentence-transformers-2.2.2\n\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n\u001b[0m","output_type":"stream"}]},{"cell_type":"code","source":"from sentence_transformers import SentenceTransformer ,util","metadata":{"execution":{"iopub.status.busy":"2023-05-20T03:00:53.454350Z","iopub.execute_input":"2023-05-20T03:00:53.454734Z","iopub.status.idle":"2023-05-20T03:00:53.937834Z","shell.execute_reply.started":"2023-05-20T03:00:53.454696Z","shell.execute_reply":"2023-05-20T03:00:53.936915Z"},"trusted":true},"execution_count":6,"outputs":[]},{"cell_type":"code","source":"model=SentenceTransformer('msmarco-distilbert-base-v3',device='cuda')","metadata":{"execution":{"iopub.status.busy":"2023-05-20T03:00:57.144179Z","iopub.execute_input":"2023-05-20T03:00:57.144890Z","iopub.status.idle":"2023-05-20T03:01:03.120161Z","shell.execute_reply.started":"2023-05-20T03:00:57.144849Z","shell.execute_reply":"2023-05-20T03:01:03.119203Z"},"trusted":true},"execution_count":7,"outputs":[{"output_type":"display_data","data":{"text/plain":"Downloading (…)da7dc/.gitattributes:   0%|          | 0.00/690 [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"ef9b0e063eab479484d742127f666233"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Downloading (…)_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"d32d4d1bcd1a4b71a242b055d39b8cad"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Downloading (…)3fc4bda7dc/README.md:   0%|          | 0.00/3.71k [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"0c3d99bbe7ac49faa4683b3fbd7355f3"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Downloading (…)c4bda7dc/config.json:   0%|          | 0.00/545 [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"85723e3a28d7454ab7a770e98e8608ae"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Downloading (…)ce_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"8dff3194162c413ea6aa4309f35cf342"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Downloading pytorch_model.bin:   0%|          | 0.00/265M [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"f41d84daf4984e5aa041aa80c8977ffd"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Downloading (…)nce_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"68dc350d8ee349a78d6f6518be5ae81d"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Downloading (…)cial_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"5239b8dc557242bc8b2232ea4d61c30d"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Downloading (…)da7dc/tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"500f4b44ea624941bfa80c533e993e99"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Downloading (…)okenizer_config.json:   0%|          | 0.00/499 [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"84442996f3f246af80207c13a559ddec"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Downloading (…)3fc4bda7dc/vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"aadce95983da4992a93e10b8b27b421d"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Downloading (…)4bda7dc/modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"b002ae03a2f344379ab429497d3dee66"}},"metadata":{}}]},{"cell_type":"code","source":"d=768\ndef search_func_qa(question,k):\n    question_vector=model.encode(question)\n    question_vector_norm=question_vector/np.linalg.norm(question_vector)\n    Distances,Indexes=index.search(question_vector_norm.reshape(1,d),k)\n    #print(*Distances)\n    #print(*Indexes)\n    docs=[data[a]['text'] for a in Indexes[0]]\n    return docs","metadata":{"execution":{"iopub.status.busy":"2023-05-20T03:09:32.795022Z","iopub.execute_input":"2023-05-20T03:09:32.795722Z","iopub.status.idle":"2023-05-20T03:09:32.801103Z","shell.execute_reply.started":"2023-05-20T03:09:32.795688Z","shell.execute_reply":"2023-05-20T03:09:32.800206Z"},"trusted":true},"execution_count":21,"outputs":[]},{"cell_type":"code","source":"search_func_qa(\"What is black death\",5)","metadata":{"execution":{"iopub.status.busy":"2023-05-20T03:04:08.184419Z","iopub.execute_input":"2023-05-20T03:04:08.184812Z","iopub.status.idle":"2023-05-20T03:04:08.229052Z","shell.execute_reply.started":"2023-05-20T03:04:08.184779Z","shell.execute_reply":"2023-05-20T03:04:08.227822Z"},"trusted":true},"execution_count":13,"outputs":[{"output_type":"display_data","data":{"text/plain":"Batches:   0%|          | 0/1 [00:00<?, ?it/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"d3a3cb365f6c4de6a47dfcd3b85c65e9"}},"metadata":{}},{"name":"stdout","text":"[0.24880955 0.2449294  0.22833182 0.21622472 0.21317157]\n[ 0  2 19 13 15]\n","output_type":"stream"},{"execution_count":13,"output_type":"execute_result","data":{"text/plain":"['A pandemic (from Greek πᾶν, pan, \"all\" and δῆμος, demos, \"people\") is an epidemic of an infectious disease that has spread across a large region, for instance multiple continents or worldwide, affecting a substantial number of people. A widespread endemic disease with a stable number of infected people is not a pandemic. Widespread endemic diseases with a stable number of infected people such as recurrences of seasonal influenza are generally excluded as they occur simultaneously in large regions of the globe rather than being spread worldwide.\\nThroughout human history, there have been a number of pandemics of diseases such as smallpox and tuberculosis. The most fatal pandemic in recorded history was the Black Death (also known as The Plague), which killed an estimated 75–200 million people in the 14th century. The term was not used yet but was for later pandemics including the 1918 influenza pandemic (Spanish flu). Current pandemics include COVID-19 (SARS-CoV-2) and HIV/AIDS.',\n 'The Antonine Plague of 165 to 180 AD, also known as the Plague of Galen (after Galen, the physician who described it), was an ancient pandemic brought to the Roman Empire by troops who were returning from campaigns in the Near East. Scholars have suspected it to have been either smallpox or measles. The plague may have claimed the life of a Roman emperor, Lucius Verus, who died in 169 and was the co-regent of Marcus Aurelius Antoninus, whose family name, Antoninus, has become associated with the pandemic. \\nAncient sources agree that the plague appeared first during the Roman siege of the Mesopotamian city Seleucia in the winter of 165–166. Ammianus Marcellinus reported that the plague spread to Gaul and to the legions along the Rhine. Eutropius stated that a large population died throughout the empire. According to the contemporary Roman historian Cassius Dio, the disease broke out again nine years later in 189 AD and caused up to 2,000 deaths a day in Rome, one quarter of those who were affected. The total death count has been estimated at 5 million, and the disease killed as much as one third of the population in some areas and devastated the Roman army.Australian sinologist and historian Rafe de Crespigny speculates that the plague may have also broken out in Eastern Han China before 166 because of notices of plagues in Chinese records. The plague affected Roman culture and literature and may have severely affected Indo-Roman trade relations in the Indian Ocean.',\n 'The Spanish flu, also known as the 1918 flu pandemic, was an unusually deadly influenza pandemic caused by the H1N1 influenza A virus. Lasting from February 1918 to April 1920, it infected 500 million people – about a third of the world\\'s population at the time – in four successive waves. The death toll is typically estimated to have been somewhere between 17 million and 50 million, and possibly as high as 100 million, making it one of the deadliest pandemics in human history.The first observations of illness and mortality were documented in the United States (in Fort Riley, Haskell County, Kansas as well as in New York City), France (Brest), Germany and the United Kingdom. To maintain morale, World War I censors minimized these early reports. Newspapers were free to report the epidemic\\'s effects in neutral Spain, such as the grave illness of King Alfonso XIII, and these stories created a false impression of Spain as especially hard hit. This gave rise to the name \"Spanish\" flu. Historical and epidemiological data are inadequate to identify with certainty the pandemic\\'s geographic origin, with varying views as to its location.\\nMost influenza outbreaks disproportionately kill the very young and the very old, with a higher survival rate for those in between, but the Spanish flu pandemic resulted in a higher-than-expected mortality rate for young adults. Scientists offer several possible explanations for the high mortality rate of the 1918 influenza pandemic. Some analyses have shown the virus to be particularly deadly because it triggers a cytokine storm, which ravages the stronger immune system of young adults. In contrast, a 2007 analysis of medical journals from the period of the pandemic found that the viral infection was no more aggressive than previous influenza strains. Instead, malnourishment, overcrowded medical camps and hospitals, and poor hygiene, all exacerbated by the recent war, promoted bacterial superinfection. This superinfection killed most of the victims, typically after a somewhat prolonged death bed.The 1918 Spanish flu was the first of two pandemics caused by H1N1 influenza A virus; the second was the 2009 swine flu pandemic.',\n \"The Pandemic Severity Assessment Framework (PSAF) is an evaluation framework which uses quadrants to evaluate both the transmissibility and clinical severity of a pandemic and to combine these into an overall impact estimate.\\nClinical severity is calculated via multiple measures including case fatality rate, case-hospitalization ratios, and deaths-hospitalizations ratios, while viral transmissibility is measured via available data among secondary household attack rates, school attack rates, workplace attack rates, community attack rates, rates of emergency department and outpatient visits for influenza-like illness.The PSAF superseded the 2007 linear Pandemic Severity Index (PSI), which assumed 30% spread and measured case fatality rate (CFR) to assess the severity and evolution of the pandemic. The United States Centers for Disease Control and Prevention (CDC) adopted the PSAF as its official pandemic severity assessment tool in 2014, and it was the official pandemic severity assessment tool listed in the CDC's National Pandemic Strategy at the time of the COVID-19 pandemic.\",\n 'The Plague of Cyprian was a pandemic that afflicted the Roman Empire about from AD 249 to 262. The plague is thought to have caused widespread manpower shortages for food production and the Roman army, severely weakening the empire during the Crisis of the Third Century. Its modern name commemorates St. Cyprian, bishop of Carthage, an early Christian writer who witnessed and described the plague. The agent of the plague is highly speculative because of sparse sourcing, but suspects have included smallpox, pandemic influenza and viral hemorrhagic fever (filoviruses) like the Ebola virus.']"},"metadata":{}}]},{"cell_type":"code","source":"a=questions[0]\nprint(a)\nqa_model(question=a,context=''.join(search_func_qa(a,5)))","metadata":{"execution":{"iopub.status.busy":"2023-05-20T03:29:47.401979Z","iopub.execute_input":"2023-05-20T03:29:47.402354Z","iopub.status.idle":"2023-05-20T03:29:52.263049Z","shell.execute_reply.started":"2023-05-20T03:29:47.402323Z","shell.execute_reply":"2023-05-20T03:29:52.262054Z"},"trusted":true},"execution_count":55,"outputs":[{"name":"stdout","text":"How many people have died during Black Death?\n","output_type":"stream"},{"output_type":"display_data","data":{"text/plain":"Batches:   0%|          | 0/1 [00:00<?, ?it/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"17503814a2124472ba161ebc2b02bf02"}},"metadata":{}},{"execution_count":55,"output_type":"execute_result","data":{"text/plain":"{'score': 0.6152188777923584,\n 'start': 7357,\n 'end': 7371,\n 'answer': '75–200 million'}"},"metadata":{}}]},{"cell_type":"code","source":"qa_model(question=\"Whose family name got associated with the Antonine Plague\",context=''.join(search_func_qa(a,5)))","metadata":{"execution":{"iopub.status.busy":"2023-05-20T03:34:30.014563Z","iopub.execute_input":"2023-05-20T03:34:30.015031Z","iopub.status.idle":"2023-05-20T03:34:34.843934Z","shell.execute_reply.started":"2023-05-20T03:34:30.014990Z","shell.execute_reply":"2023-05-20T03:34:34.843077Z"},"trusted":true},"execution_count":63,"outputs":[{"output_type":"display_data","data":{"text/plain":"Batches:   0%|          | 0/1 [00:00<?, ?it/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"7c74a130baf94ec8af60b7dd30749c57"}},"metadata":{}},{"execution_count":63,"output_type":"execute_result","data":{"text/plain":"{'score': 0.6712337732315063,\n 'start': 5547,\n 'end': 5556,\n 'answer': 'Antoninus'}"},"metadata":{}}]},{"cell_type":"code","source":"search_func_qa(\"Whose family name got associated with the Antonine Plague\",5)","metadata":{"execution":{"iopub.status.busy":"2023-05-20T03:34:16.308209Z","iopub.execute_input":"2023-05-20T03:34:16.308677Z","iopub.status.idle":"2023-05-20T03:34:16.345010Z","shell.execute_reply.started":"2023-05-20T03:34:16.308639Z","shell.execute_reply":"2023-05-20T03:34:16.344072Z"},"trusted":true},"execution_count":62,"outputs":[{"output_type":"display_data","data":{"text/plain":"Batches:   0%|          | 0/1 [00:00<?, ?it/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"09a8fadb0f76466597431ed6e81c7515"}},"metadata":{}},{"execution_count":62,"output_type":"execute_result","data":{"text/plain":"['The Antonine Plague of 165 to 180 AD, also known as the Plague of Galen (after Galen, the physician who described it), was an ancient pandemic brought to the Roman Empire by troops who were returning from campaigns in the Near East. Scholars have suspected it to have been either smallpox or measles. The plague may have claimed the life of a Roman emperor, Lucius Verus, who died in 169 and was the co-regent of Marcus Aurelius Antoninus, whose family name, Antoninus, has become associated with the pandemic. \\nAncient sources agree that the plague appeared first during the Roman siege of the Mesopotamian city Seleucia in the winter of 165–166. Ammianus Marcellinus reported that the plague spread to Gaul and to the legions along the Rhine. Eutropius stated that a large population died throughout the empire. According to the contemporary Roman historian Cassius Dio, the disease broke out again nine years later in 189 AD and caused up to 2,000 deaths a day in Rome, one quarter of those who were affected. The total death count has been estimated at 5 million, and the disease killed as much as one third of the population in some areas and devastated the Roman army.Australian sinologist and historian Rafe de Crespigny speculates that the plague may have also broken out in Eastern Han China before 166 because of notices of plagues in Chinese records. The plague affected Roman culture and literature and may have severely affected Indo-Roman trade relations in the Indian Ocean.',\n 'The Plague of Cyprian was a pandemic that afflicted the Roman Empire about from AD 249 to 262. The plague is thought to have caused widespread manpower shortages for food production and the Roman army, severely weakening the empire during the Crisis of the Third Century. Its modern name commemorates St. Cyprian, bishop of Carthage, an early Christian writer who witnessed and described the plague. The agent of the plague is highly speculative because of sparse sourcing, but suspects have included smallpox, pandemic influenza and viral hemorrhagic fever (filoviruses) like the Ebola virus.',\n 'The 1929–1930 psittacosis pandemic, also known as the psittacosis outbreak of 1929–1930 and the great parrot fever pandemic, was a series of simultaneous outbreaks of psittacosis (parrot fever) which, accelerated by the breeding and transportation of birds in crowded containers for the purpose of trade, was initially seen to have its origin in parrots from South America. It was shortly found to have spread from several species of birds from several countries worldwide to humans between mid 1929 and early 1930. Diagnosed by its clinical features and link to birds, it affected around 750 to 800 people globally, with a mortality of 15%. Its mode of transmission to humans by mouth-to-beak contact or inhaling dried bird secretions and droppings was not known at the time. The cause, Chlamydia psittaci, which usually remains dormant in birds until activated by stress of capture and confinement, was discovered after the pandemic.\\nCases were reported in mid 1929, in Birmingham, United Kingdom, and linked to parrots from Buenos Aires, Argentina, where an ongoing outbreak of the disease had led to cautioning bird owners to declare their sick parrots. The origin of the outbreak in the Argentine city of Córdoba was traced to an import of 5,000 parrots from Brazil. Although the Argentine parrot trade was stopped, a number of birds were illegally sold on to visitors to its seaports, with the consequence that psittacosis was transmitted to several countries.\\nIn November 1929, reports of cases among an Argentine theatrical group in Córdoba made it into the local press. In January 1930, when cases of an atypical pneumonia in one family, with the death of their parrot, appeared in Maryland, United States, a link was made to the story of the theatrical group, and \"parrot fever\" made headlines in the American press. Following further cases, bans on parrot trades were implemented, and subsequently cases were reported in several other countries, including Germany, France and Australia. The origin was understood to have been the importation of green Amazon parrots from South America. Later, the principal source of the disease in the U.S. was domestic lovebirds raised in Californian aviaries, and sold to mainly housewives and widows.\\nThe impact of the outbreak on the U.S. Hygienic Laboratory, with 16 of its workers affected, including two deaths, led to the formation of the National Institute of Health.',\n 'Swine influenza is an infection caused by any one of several types of swine influenza viruses. Swine influenza virus (SIV) or swine-origin influenza virus (S-OIV) is any strain of the influenza family of viruses that is endemic in pigs. As of 2009, the known SIV strains include influenza C and the subtypes of  influenza A known as H1N1, H1N2, H2N1, H3N1, H3N2, and H2N3.\\nSwine influenza virus is common throughout pig populations worldwide. Transmission of the virus from pigs to humans is not common and does not always lead to human flu, often resulting only in the production of antibodies in the blood. If transmission does cause human flu, it is called zoonotic swine flu. People with regular exposure to pigs are at increased risk of swine flu infection.\\nAround the mid-20th century, identification of influenza subtypes became possible, allowing accurate diagnosis of transmission to humans. Since then, only 50 such transmissions have been confirmed. These strains of swine flu rarely pass from human to human. Symptoms of zoonotic swine flu in humans are similar to those of influenza and of influenza-like illness in general, namely chills, fever, sore throat, muscle pains, severe headache, coughing, weakness, shortness of breath, and general discomfort.\\nIt is estimated that in the 2009 flu pandemic 11–21% of the then global population (of about 6.8 billion), or around 700 million to 1.4 billion people, contracted the illness—more in absolute terms than the Spanish flu pandemic. Actual fatalities ranged between 12,000 and 18,000. However, in a 2012 study, the CDC estimated more than 284,000 possible fatalities worldwide, with range from 150,000 to 575,000.\\nIn August 2010, the World Health Organization declared the swine flu pandemic officially over.Subsequent cases of swine flu were reported in India in 2015, with over 31,156 positive test cases and 1,841 deaths up to March 2015.',\n \"The People's Republic of China's first reported AIDS case was identified in 1985 in a dying tourist. In 1989, the first indigenous cases were reported as an outbreak in 146 infected heroin users in Yunnan province, near China's southwest border.Yunnan is the area most affected by HIV/AIDS in China. In 1989 first infections appeared among needle sharing drug users near the Burmese border. Up until 1993, the disease had remained a problem in the border areas before mobile people (truck drivers, construction and migrant workers and travelers) brought the virus further into the country. In 1995, the provinces of Sichuan and Xinjiang reported their first HIV cases, and by 1998, the virus had spread all over China.\\nLow awareness of the disease among China's general population appears to be a major culprit. Most Chinese consider HIV/AIDS as a foreign issue, and even educated people are less knowledgeable of the virus, its transmission and prevention, than people in other countries. Until recently, the use of condoms was not very common, even among sex workers and their clients. As a result, the epidemic has spread from high-risk groups (drug users, sex workers, unsafe blood donors) to the general population.\"]"},"metadata":{}}]},{"cell_type":"code","source":"","metadata":{},"execution_count":null,"outputs":[]}]}